apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav
data:
  freshclam.conf: |
    PidFile /tmp/freshclam.pid
    DatabaseOwner clamav
    NotifyClamd /etc/clamav/clamd.conf
    ScriptedUpdates yes
    DatabaseMirror database.clamav.net
    UpdateLogFile /var/log/clamav/freshclam.log
  clamd.conf: |
    DatabaseDirectory /var/lib/clamav
    TemporaryDirectory /tmp
    LogTime yes
    LogFileMaxSize 2M
    LogSyslog yes
    PidFile /tmp/clamd.pid
    LocalSocket /run/clamav/clamd.sock
    TCPSocket 3310
    Foreground yes
    User clamav

    # StreamMaxLength 100M
    # MaxScanSize 300M
    # MaxFileSize 100M
    # MaxRecursion 30
    # MaxFiles 50000
    # MaxEmbeddedPE 40M
    # MaxHTMLNormalize 40M
    # MaxHTMLNoTags 2M
    # MaxScriptNormalize 5M
    # MaxZipTypeRcg 1M
    # MaxPartitions 128
    # MaxIconsPE 200
    # PCREMatchLimit 10000
    # PCRERecMatchLimit 10000
