apiVersion: v1
kind: Service
metadata:
  name: clamav-api
  labels:
    app: clamav-api
spec:
  type: ClusterIP
  selector:
    app: clamav-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080